import unittest

from tools.update_item_catalog import parse_catalog


class ItemCatalogGeneratorTests(unittest.TestCase):
    @staticmethod
    def _html(version="0.221.12", count=300):
        rows = []
        for index in range(count):
            rows.append(
                "<tr>"
                f"<td>Prefab{index}<br><img src='Prefab{index}.png'></td>"
                f"<td>asset{index}</td>"
                f"<td>$item_{index}</td>"
                f"<td>Display {index}</td>"
                "<td>Material</td>"
                "<td>Description</td>"
                "</tr>"
            )
        return (
            "<html><body>"
            f"<p>This file is automatically generated from Valheim {version} using JotunnDoc.</p>"
            "<table><tr><th>Item</th><th>AssetID</th><th>Token</th><th>English Name</th>"
            "<th>Type</th><th>Description</th></tr>"
            + "".join(rows)
            + "</table></body></html>"
        )

    def test_parses_versioned_selectable_catalog(self):
        catalog = parse_catalog(self._html(), "https://example.invalid/items", "0.221.12")
        self.assertEqual(catalog["game_version"], "0.221.12")
        self.assertEqual(catalog["item_count"], 300)
        self.assertEqual(catalog["selectable_item_count"], 300)
        self.assertEqual(catalog["items"][0]["prefab"], "Prefab0")

    def test_refuses_unreviewed_game_version_change(self):
        with self.assertRaisesRegex(RuntimeError, "reports Valheim 1.0.0"):
            parse_catalog(self._html(version="1.0.0"), "https://example.invalid/items", "0.221.12")

    def test_refuses_suspiciously_small_catalog(self):
        with self.assertRaisesRegex(RuntimeError, "suspiciously small catalog"):
            parse_catalog(self._html(count=20), "https://example.invalid/items", "0.221.12")


if __name__ == "__main__":
    unittest.main()
